#系统地址设置
deploy:
  server:
    ip: ${SERVER_SERVER_IP:127.0.0.1}
    port: ${SERVER_SERVER_PORT:8080}
    context-path: ${SERVER_SERVER_CONTEXT_PATH:/}
    application-name: validator-demo
spring:
  profiles:
    include: base,log