server:
  ip: ${deploy.server.ip}
  port: ${deploy.server.port}
  undertow:
    #每块buffer的空间大小,越小的空间被利用越充分
    bufferSize: 1024
    #是否分配的直接内存
    directBuffers: true
    threads:
      #阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
      io: 8
      worker: 8
  servlet:
    context-path: ${deploy.server.context-path}
spring:
  application:
    name: ${deploy.server.application-name}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB